version: "3.7"

services:
  main:
    build:
      context: ./
    ports:
      - 5000:5000
  tests:
    image: mrexpen/planet_olymp_phase1
    pull_policy: always
    ports:
      - "8090:8080"
    depends_on:
      - main
    environment:
      SERVER_URL: http://main:5000
      STAGE: all
      # all - запуск всех тестов из трёх доступных этапов
      # 0, 1 или 2 - запуск тестов для соответствующего этапа
