"""empty message

Revision ID: 542f5012d5d5
Revises: af71b028f384
Create Date: 2023-02-05 17:12:18.748842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '542f5012d5d5'
down_revision = 'af71b028f384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=False))
        batch_op.drop_column('password')
        batch_op.drop_column('last_name')
        batch_op.drop_column('email')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=16), nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=55), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=16), nullable=False))
        batch_op.add_column(sa.Column('password', sa.TEXT(), nullable=False))
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
