"""empty message

Revision ID: af71b028f384
Revises: 
Create Date: 2023-02-04 19:17:41.732833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af71b028f384'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=16), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('role')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=16), nullable=False))
        batch_op.add_column(sa.Column('role', sa.TEXT(), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
