"""empty message

Revision ID: e021a706c987
Revises: 542f5012d5d5
Create Date: 2023-02-09 19:43:45.413628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e021a706c987'
down_revision = '542f5012d5d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visited_locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_time_of_visiting', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visited_locations', schema=None) as batch_op:
        batch_op.drop_column('date_time_of_visiting')

    # ### end Alembic commands ###
